using task7;
task7.Math math = new task7.Math();
System.Console.WriteLine(math.Abs(-12.5));
System.Console.WriteLine(math.Abs(12.598));
System.Console.WriteLine(math.Abs(-12));
System.Console.WriteLine(math.Pow(5,2));
System.Console.WriteLine(math.Sqrt(625));
System.Console.WriteLine(math.Max(10, 5));
System.Console.WriteLine(math.Min(10, 5));
System.Console.WriteLine(math.Pow(5,3));
System.Console.WriteLine(math.Sqrt(729));